version: "3.8"

services:
  db:
    image: postgres:16
    container_name: bcb-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: bcb-app
    container_name: bcb-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

volumes:
  postgres_data:
